# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    # mode: HTML5
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages_zh_CN
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      
# 配置.xml文件路径
mybatis:
  mapper-locations: classpath*:mapper/*.xml
#配置模型路径
  type-aliases-package: com.ldh.bk